### PR TITLE
Full path to python isn't needed

### PR DESCRIPTION
**Pull request by poige**
(it works this way)

### CODE REVIEW

**Comment by lastsky** [comment]
it works but not on all operating systems. i will think what to do with that... thanks... now this moment i dunno.

**Comment by poige** [comment]
Nope, it works everywhere where python is in standard path. Since you're explicitly invoking it in `/usr/bin` my version would work just fine or even better. ;)

**Comment by lastsky** [comment]
it's a some type of fuckup for me: smartos, gentoo, solaris. before managing host i need to install python 2.X. thats why i always set this var.

it works everywhere where python is in standard path, agree.

**Comment by lastsky** [comment]
now this moment playbook has no adaptation for different OS. in plans: 10x hosts with different OS and managing ini on them.

**Comment by poige** [comment]
Well, just shared knowledge; lots of ansible users think it has to be full qualified path to python. ;)

**Comment by lastsky** [comment]
examples added. please check what i mean.

**Comment by lastsky** [comment]
i dunno how to implement that without defining var in inventory file.... really dont.

**Comment by lastsky** [comment]
please check examples in new hosts.ini file

**Pull request closed without merging**
